### ISSUE TITLE
Some suggestions for documentation

### ISSUE THREAD

**Issue by psychemistz** [data2intelligence/SpaCE#2]
I have some suggestions for documentation related to analyzing visium datasets posted here (https://data2intelligence.github.io/SpaCE/articles/visium_BC.html).

1) In SpaCE analysis, If a gene exhibits zero counts, it is removed by the "rm_zeroRows" function.
    Also, if there are duplicate genes, the gene with the highest total counts remains and all other duplicate genes are removed.
    I'd like to suggest including this information in the article so that the reader has an explicit understanding of how SpaCE handles 
    the problem of zero-count genes and duplicate genes.

2) The meaning of the column names in the expression matrix returned by "create.SpaCE.object" is not explicitly defined in the documentation. I think it's the (x, y) position from the origin, but it's not clear where the origin is. It's a good idea to explicitly provide where the origin of the coordinates is and what exactly the x and y mean (i.e. the horizontal and vertical order of each spot).

3) Images returned from "SpaCE.visualize.metrics" represent the number of UMIs per spot (itemQC= "UMI" option) or the number of genes with at least 1 UMI for a particular spot (itemQC= "Gene" option). Therefore, the "UMI" option represents spots containing large amounts of RNA samples and the "Gene" option represents the number of genes with at least one UMI expression in a particular spot. Readers may have difficulty understanding the meaning of these options, as the current documentation lacks such explanations. I would suggest providing this information in the article. If possible, I would suggest to include reference page in package home. This is because the reference page allows user to better understand each option in the package. An example of reference page is shown in this url (https://psychemistz.github.io/ovltools/reference/index.html)

4) The meaning of values in "SpaCE_obj@results$deconvolution" table is not obvious. I thought that it is a percentage of cell type in a spot  but when I added up cell type deconvolution results in a spot, it returned >1 values. For example, column sum of "50x102" spot was 1.320. Also, the meaning of "spot size" and "spot alpha" require more explanation. It seems that SpaCE utilizes constraint optimization based on known dictionary of cell type to deconvolute cell types in spatial transcriptome dataset. If it is possible, it would be better to provide performance comparison results for other cell type deconvolution algorithms. (For example, figure 4 of this article (https://www.nature.com/articles/s41592-022-01480-9))

5) word speling issue. 
    (1) cell faction => cell fraction in "Deconvolve ST data" section 

6) The meaning of the cancer cell status fraction is also not clear. Again, adding the two cancer cell states (states A and B) fraction did not return 1 for all cases (median 0.6622). 

7) in "Deconvolution with a matched scRNA-seq data set" tutorial,
    code snippet need to be updated since the table only contains 2 columns. 
    sc_annotation[1:6,1:5] => sc_annotation[1:6,]

8) SpaCE.visualize.gene(SpaCE_obj,"TM4SF1") function does not work. It returns following error.
    "Error in colSums(expression) : 'x' must be at least 2D array"

**Comment by beibeiru** [comment]
Hi, Seongyong,

Thanks a lot for your feedback. I have revised the documentation according to your comments.


> 1. In SpaCE analysis, If a gene exhibits zero counts, it is removed by the "rm_zeroRows" function. Also, if there are duplicate genes, the gene with the highest total counts remains and all other duplicate genes are removed. I'd like to suggest including this information in the article so that the reader has an explicit understanding of how SpaCE handles the problem of zero-count genes and duplicate genes.

Already added the following description in the tutorial.
"In this step, the genes exhibiting zero UMI counts across spots will be removed. Also, if there are duplicated gene symbols, the gene with the highest total counts remains and all other duplicated genes are removed."

> 2. The meaning of the column names in the expression matrix returned by "create.SpaCE.object" is not explicitly defined in the documentation. I think it's the (x, y) position from the origin, but it's not clear where the origin is. It's a good idea to explicitly provide where the origin of the coordinates is and what exactly the x and y mean (i.e. the horizontal and vertical order of each spot).

Already added the following description in the tutorial.
"The UMI count matrix is stored in SpaCE_obj@input$counts as a sparse matrix. Each row represents a gene whereas each column is a spot. Of note, the column name is the ID of spots with a format “AxB”, which means the horizontal (A) and vertical (B) order of each spot, respectively."

> 3. Images returned from "SpaCE.visualize.metrics" represent the number of UMIs per spot (itemQC= "UMI" option) or the number of genes with at least 1 UMI for a particular spot (itemQC= "Gene" option). Therefore, the "UMI" option represents spots containing large amounts of RNA samples and the "Gene" option represents the number of genes with at least one UMI expression in a particular spot. Readers may have difficulty understanding the meaning of these options, as the current documentation lacks such explanations. I would suggest providing this information in the article. 

Already added the following description in the tutorial.
"Specifically, the "UMI" option presents the overall UMI counts within a spot while the "Gene" option represents the number of expressed genes (i.e., genes with at least one UMI count) in a particular spot."

> If possible, I would suggest to include reference page in package home. This is because the reference page allows user to better understand each option in the package. An example of reference page is shown in this url (https://psychemistz.github.io/ovltools/reference/index.html)

Already added.

> 4. The meaning of values in "SpaCE_obj@results$deconvolution" table is not obvious. I thought that it is a percentage of cell type in a spot  but when I added up cell type deconvolution results in a spot, it returned >1 values. For example, column sum of "50x102" spot was 1.320. 

 I add the following description in the tutorial.
"Of note, the value from deconvolution results represents the fraction of cell types. User may find that the fraction sum of all cell types in a spot (column) is beyond 1. This is because SpaCE outputs the cell fractions for both major lineages and their corresponding sublineages, e.g., T CD4 as well as Th1, Th2... . "

> Also, the meaning of "spot size" and "spot alpha" require more explanation. It seems that SpaCE utilizes constraint optimization based on known dictionary of cell type to deconvolute cell types in spatial transcriptome dataset. 

I add the following description in the tutorial.
"Of note, each dot represents an ST spot and user can adjust the size and opacity of spots."

> If it is possible, it would be better to provide performance comparison results for other cell type deconvolution algorithms. (For example, figure 4 of this article (https://www.nature.com/articles/s41592-022-01480-9))

We had a comprehensive comparison in our manuscript.

> 5. word speling issue.
>    (1) cell faction => cell fraction in "Deconvolve ST data" section

Fixed it

> 6. The meaning of the cancer cell status fraction is also not clear. Again, adding the two cancer cell states (states A and B) fraction did not return 1 for all cases (median 0.6622).

I add the following description in the tutorial.
"Similar to the deconvolution of immune major lineages into sublineages, the overall malignant cell fraction would be decomposed to multiple cancer cell states. Thus, the sum fraction of cancer cell states equals to the malignant cell fraction for each spot. "

> 7. in "Deconvolution with a matched scRNA-seq data set" tutorial,
>    code snippet need to be updated since the table only contains 2 columns.
>    sc_annotation[1:6,1:5] => sc_annotation[1:6,]

Fixed it

> 8. SpaCE.visualize.gene(SpaCE_obj,"TM4SF1") function does not work. It returns following error.
>    "Error in colSums(expression) : 'x' must be at least 2D array"

Fixed it


Best,
Beibei

**Comment by data2intelligence** [comment]
Hi, Seongyong,

Thank you very much for these suggestions! Very helpful.



Sincerely, Peng


On Aug 17, 2022, at 3:18 PM, Beibei Ru ***@***.******@***.***>> wrote:



Hi, Seongyong,

Thanks a lot for your feedback. I have revised the documentation according to your comments.

  1.  In SpaCE analysis, If a gene exhibits zero counts, it is removed by the "rm_zeroRows" function. Also, if there are duplicate genes, the gene with the highest total counts remains and all other duplicate genes are removed. I'd like to suggest including this information in the article so that the reader has an explicit understanding of how SpaCE handles the problem of zero-count genes and duplicate genes.

Already added the following description in the tutorial.
"In this step, the genes exhibiting zero UMI counts across spots will be removed. Also, if there are duplicated gene symbols, the gene with the highest total counts remains and all other duplicated genes are removed."

  1.  The meaning of the column names in the expression matrix returned by "create.SpaCE.object" is not explicitly defined in the documentation. I think it's the (x, y) position from the origin, but it's not clear where the origin is. It's a good idea to explicitly provide where the origin of the coordinates is and what exactly the x and y mean (i.e. the horizontal and vertical order of each spot).

Already added the following description in the tutorial.
"The UMI count matrix is stored in ***@***.***$counts as a sparse matrix. Each row represents a gene whereas each column is a spot. Of note, the column name is the ID of spots with a format “AxB”, which means the horizontal (A) and vertical (B) order of each spot, respectively."

  1.  Images returned from "SpaCE.visualize.metrics" represent the number of UMIs per spot (itemQC= "UMI" option) or the number of genes with at least 1 UMI for a particular spot (itemQC= "Gene" option). Therefore, the "UMI" option represents spots containing large amounts of RNA samples and the "Gene" option represents the number of genes with at least one UMI expression in a particular spot. Readers may have difficulty understanding the meaning of these options, as the current documentation lacks such explanations. I would suggest providing this information in the article.

Already added the following description in the tutorial.
"Specifically, the "UMI" option presents the overall UMI counts within a spot while the "Gene" option represents the number of expressed genes (i.e., genes with at least one UMI count) in a particular spot."

If possible, I would suggest to include reference page in package home. This is because the reference page allows user to better understand each option in the package. An example of reference page is shown in this url (https://psychemistz.github.io/ovltools/reference/index.html<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpsychemistz.github.io%2Fovltools%2Freference%2Findex.html&data=05%7C01%7Cpeng.jiang%40nih.gov%7C7aaabc8179284e27bc8d08da8085473d%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637963607164580402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s2Lz%2Fk3OrlupbNOHzwSV2OUDjlE2jGYd%2FVHnUt3GTsE%3D&reserved=0>)

Already added.

  1.  The meaning of values in ***@***.***$deconvolution" table is not obvious. I thought that it is a percentage of cell type in a spot but when I added up cell type deconvolution results in a spot, it returned >1 values. For example, column sum of "50x102" spot was 1.320.

I add the following description in the tutorial.
"Of note, the value from deconvolution results represents the fraction of cell types. User may find that the fraction sum of all cell types in a spot (column) is beyond 1. This is because SpaCE outputs the cell fractions for both major lineages and their corresponding sublineages, e.g., T CD4 as well as Th1, Th2... . "

Also, the meaning of "spot size" and "spot alpha" require more explanation. It seems that SpaCE utilizes constraint optimization based on known dictionary of cell type to deconvolute cell types in spatial transcriptome dataset.

I add the following description in the tutorial.
"Of note, each dot represents an ST spot and user can adjust the size and opacity of spots."

If it is possible, it would be better to provide performance comparison results for other cell type deconvolution algorithms. (For example, figure 4 of this article (https://www.nature.com/articles/s41592-022-01480-9<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fs41592-022-01480-9&data=05%7C01%7Cpeng.jiang%40nih.gov%7C7aaabc8179284e27bc8d08da8085473d%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637963607164580402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dkbgq1d57IaQ5XNdYUDNsTdg9EvlOYEG9OUShX9HrRI%3D&reserved=0>))

We had a comprehensive comparison in our manuscript.

  1.  word speling issue.
(1) cell faction => cell fraction in "Deconvolve ST data" section

Fixed it

  1.  The meaning of the cancer cell status fraction is also not clear. Again, adding the two cancer cell states (states A and B) fraction did not return 1 for all cases (median 0.6622).

I add the following description in the tutorial.
"Similar to the deconvolution of immune major lineages into sublineages, the overall malignant cell fraction would be decomposed to multiple cancer cell states. Thus, the sum fraction of cancer cell states equals to the malignant cell fraction for each spot. "

  1.  in "Deconvolution with a matched scRNA-seq data set" tutorial,
code snippet need to be updated since the table only contains 2 columns.
sc_annotation[1:6,1:5] => sc_annotation[1:6,]

Fixed it

  1.  SpaCE.visualize.gene(SpaCE_obj,"TM4SF1") function does not work. It returns following error.
"Error in colSums(expression) : 'x' must be at least 2D array"

Fixed it

Best,
Beibei

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FSpaCE%2Fissues%2F2%23issuecomment-1218398956&data=05%7C01%7Cpeng.jiang%40nih.gov%7C7aaabc8179284e27bc8d08da8085473d%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637963607164580402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XptcCXkXk88ieIcj%2BH0l3wyWFHcaZi7TuEy3YEP%2FaR4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREF4GLYU4B5QXDKQLZOLVZU3IPANCNFSM56PZPGHA&data=05%7C01%7Cpeng.jiang%40nih.gov%7C7aaabc8179284e27bc8d08da8085473d%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637963607164580402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YV7rN8KVt3hc%2FSGkiRe1FsisgHxPEiMKgGdW51rW7vg%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
